title: Memcache
author: Dataloop.IO
version: 1.0.0
processes:
    - /usr/bin/memcached
description: high-performance, distributed memory object caching system metrics
icon:
    name: memcache
    background: dimgray
    foreground: lightseagreen
