title: Google Analytics
author: Dataloop.IO
version: 1.1.0
description: Add metrics from Google Analytics to your dashboards.
instructions_required: true
icon:
    name: website
    background: "#F7981E"
    foreground: "#EE5A30"