title: Varnish
author: Dataloop.IO
version: 1.0.0
processes:
    - varnishd
description: All of the metrics from the varnishstat command.
icon:
    name: varnish
    background: black
    foreground: cornflowerblue
