title: External Services
author: DevOps Guys ltd.
version: 1.0.0
description: External Service Platform Status Monitoring
instructions_required: true
icon:
    name: process
    background: white
    foreground: black
